index:
    path: /
    controller: App\Api\Controller\HomeController::index

new_reservation:
    path: /new
    controller: App\Api\Controller\Reservation\NewReservationController::newReservation

room_seeker:
    path: /room_seeker
    controller: App\Api\Controller\Reservation\RoomSeekerController::roomSeeker