index:
    path: /
    controller: App\Controller\HomeController::index

new_reservation:
    path: /new
    controller: App\Controller\reservation\NewReservationController::newReservation

room_seeker:
    path: /room_seeker
    controller: App\Controller\reservation\RoomSeekerController::roomSeeker